version: "3.8"
name: "event-runner-localtest"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka1:
    image: bitnami/kafka:latest
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:9092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:9092
    depends_on:
      - kafka1
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./cert:/cert
    command: redis-server --requirepass "development.password" --port 6379
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    hostname: redis-commander
    restart: always
    volumes:
      - ./cert:/cert
    environment:
      - REDIS_HOSTS=local:redis:6379:0:development.password
    ports:
    - "8081:8081"
    depends_on:
      - redis