version: "3.8"

services:
  zookeeper:
    image: 'zookeeper:latest'
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'wurstmeister/kafka:latest'
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=127.0.0.1:9092
    depends_on:
      - kafka
  redis:
    image: redis:latest
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./cert:/cert
    command: redis-server --requirepass "development.password" --port 6379
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    hostname: redis-commander
    restart: always
    volumes:
      - ./cert:/cert
    environment:
      - REDIS_HOSTS=local:redis:6379:0:development.password
    ports:
    - "8081:8081"
    depends_on:
      - redis